In [1]:
import numpy as np

In [2]:
array_1D = np.random.randint(0,100,100)
print(array_1D)

[34 14 39 30 47 20 92 15 78 51  0 61 75 39 55 23 41 49 30 73 78 34 57 41
  5 57 61 40 36 90 81 13  9 29 23 47 21 65 14 16 72 26 91 30 91 31 99 18
 65 74 32 47 23 96  0 92 82 38 39 22 22 11  7 78 28 72 67 23  1 44 63 78
 69 69 96 32 53  4  1 85 15 91 95 89 26 45 64 97 98 24 10 54 70 90  5  9
 53 99  7 17]


In [3]:
print('Количество осей: ',array_1D.ndim)
print('Форма массива: ',array_1D.shape)
print('Количество значений: ',array_1D.size)

Количество осей:  1
Форма массива:  (100,)
Количество значений:  100


In [4]:
print(array_1D[0])

34


In [5]:
print(array_1D[31])

13


In [8]:
print(array_1D[-2])

7


In [16]:
mas = np.ones(15)
mas[::3] = 2
print(mas)

[2. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 1.]


In [21]:
array = np.zeros ((7,7))
print(array)
array[3]=1


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
